server:
  port: 0   # 0 이라고 설정하면 random port 를 사용하겠다는 의미로, 사용 가능한 임의의 port 를 사용

spring:
  application:
    name: user-service
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    # service-url -> user service application 은 Eureka server 에 등록 될 client 역할을 하는 application, 이 때 server 의 위치를 지정하는 property
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
