server:
  port: 9001

spring:
  application:
    name: user-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # service-url -> user service application ? Eureka server ? ?? ? client ??? ?? application, ? ? server ? ??? ???? property
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
